export default {
    message: {
        postLoan: "Post-loan",
        logout: "Logout",
        switchLanguage: "Switch Language",
        collectionAgency: "Collection Agency",
        agency: "Agency",
        collectionPersonnel: "Collection Personnel",
        pendingCollectionList: "Pending Collection List",
        completedCollectionList: "Completed Collection List",
        agencyName: "Agency Name",
        status: "Status",
        query: "Query",
        reset: "Reset",
        addAgency: "Add Agency",
        editAgency: "Edit Agency",
        agencyManager: "Agency Manager",
        numberOfCollectionAccounts: "Number of Collection Accounts",
        numberOfMarketingAccounts: "Number of Marketing Accounts",
        action: "Action",
        disable: "Disable",
        enable: "Enable",
        all: "All",
        collectionAccount: "Collection Account",
        marketingAccount: "Marketing Account",
        position: "Position",
        overdueStatus: "Overdue Status",
        assigned: "Assigned",
        add: "Add",
        import: "Import",
        export: "Export",
        templateDownload: "Template Download",
        addCollectionPersonnel: "Add Collection Personnel",
        editCollectionPersonnel: "Edit Collection Personnel",
        importCollectionPersonnel: "Import Collection Personnel",
        addMarketingPersonnel: "Add Marketing Personnel",
        editMarketingPersonnel: "Edit Marketing Personnel",
        importMarketingUser: "Import Marketing User",
        cancel: "Cancel",
        ensure: "Ensure",
        password: "Password",
        accountManage: "Account Manage",
        accountList: "Account List",
        nickname: "Nickname",
        account: "Account",
        role: "Role",
        delete: "Delete",
        edit: "Edit",
        username: "Username",
        yes: "Yes",
        no: "No",
        collectionSpecialist: "Collection specialist",
        collectionSupervisor: "Collection Supervisor",
        collectionManager: "Collection Manager",
        specialist: "specialist",
        supervisor: "Supervisor",
        manager: "Manager",
        reduceBalance: "Reduce Balance",
        userphone: "User Phone",
        overdueStage: "Overdue stage",
        followUPResults: "Follow-up results",
        overdueDays: "Overdue days",
        orderID: "Order ID",
        platformTags: "Order tags",
        productTag: "Product tags",
        followUp: "Follow-up",
        contractAmount: "Contract Amount",
        admin: "Admin",

        addAdmin: "Add Account",
        adminNickname: "Account Nickname",
        adminUsername: "Account Username",
        adminPassword: "Account Password",
        adminRole: "Account Role",
        editAdmin: "Edit Account",
        editPassword: "Edit Password",
        isDeleteAdminConfirmTitle: "Are you sure to delete this account?",

        confirmButtonText: "Confirm",
        cancelButtonText: "Cancel",
        closeButtonText: "Close",
        deleteSuccess: "Delete Success",
        deleteFail: "Delete Fail",
        danger: "Danger",
        warning: "Warning",
        info: "Info",
        success: "Success",
        error: "Error",
        warning: "Warning",
        loading: "Loading",
        noData: "No Data",

        "RepaymentPlanID": "Repayment Plan ID",
        "PlatformTag": "Order Tag",
        "ProductTag": "Product Tag",
        "ContractAmount": "Contract Amount",
        "Deadline": "Deadline",
        "OverdueFee": "Overdue Fee",
        "OverdueDays": "Overdue Days",
        "AmountRepaid": "Amount Repaid",
        "AmountWaived": "Amount Waived",
        "TotalRepaymentAmount": "Total Repayment Amount",
        "ExtensionRepaymentAmount": "Extension Repayment Amount",
        "WAContact": "WA Contact",
        "UserName": "User Name",
        "Gender": "Gender",
        "ProductName": "Product Name",
        "Email": "Email",
        "PhoneNumber": "Phone Number",
        "Self": "Self",
        "EmergencyContact1": "Emergency Contact 1",
        "EmergencyContact2": "Emergency Contact 2",
        "Parents": "Parents",
        "Spouse": "Spouse",
        "Children": "Children",
        "Other": "Other",
        "RepaymentRecord": "Repayment Record",
        "CreationTime": "Creation Time",
        "RepaymentMethod": "Repayment Method",
        "RepaymentType": "Repayment Type",
        "FullRepayment": "Full Repayment",
        "ExtendedRepayment": "Extended Repayment",
        "PaymentOrderNumber": "Payment Order Number",
        "AmountDue": "Amount Due",
        "PaymentStatus": "Payment Status",
        "AmountCredited": "Amount Credited",
        "Actions": "Actions",
        "Edit": "Edit",
        "Delete": "Delete",
        "RepaymentLink": "Repayment Link",
        "ApplyForWaiver": "Apply for Waiver",
        "ApplyForBalanceAdjustment": "Apply for Balance Adjustment",
        "FollowUpRecord": "FollowUp Record",
        "OverdueStage": "Overdue Stage",
        "FollowUpTime": "FollowUp Time",
        "FollowUpAccount": "FollowUp Account",
        "FollowUpTarget": "FollowUp Target",
        "PhoneNumberFollowUp": "Phone Number",
        "FollowUpResult": "FollowUp Result",
        "AddFollowUp": "Add FollowUp",
        "PANCard": "PAN Card",
        "FacePhoto": "Face Photo",
        "newCustomer": "New Customer",
        "oldCustomer": "Old Customer",
        "repaymentAmount": "Repayment Amount",
        "lastLoginTime": "Last time the app was opened",
        "lastRequestRepaymentTime": "Last payment code acquisition time",
        "isTodayRepayment": "Is Today's Repayment",
        "followUpCounts": "Follow-up Counts",
        "lastFollowUpResult": "Last Follow-up Result",
        "lastFollowUpTime": "Last Follow-up Time",
        "lastFollowUpRecord": "Last Follow-up Record",
        "collector": "Follow up people",
        "action": "Action",
        "followUp": "Follow Up",

        "EditFollowUp": "Edit FollowUp",
        "FollowUpTarget": "FollowUp Target",
        "FollowUpResult": "FollowUp Result",
        "FollowUpRecord": "FollowUp Record",
        "PleaseSelect": "Please Select",
        "PleaseInput": "Please Input",
        "PleaseInputUsername": "Please Input 6-8 Bit Number Or Letter",
        "PTP": "PTP",
        "FinancialDifficulty": "Financial Difficulty",
        "NoAnswer": "No Answer",
        "PhoneOff": "Phone Off",
        "InvalidNumber": "Invalid Number",
        "BadAttitude": "Bad Attitude",
        "PleaseEnterFollowUpRecord": "Please Enter FollowUp Record",
        "Cancel": "Cancel",
        "Confirm": "Confirm",

        "ApplyForBalanceAdjustment": "Apply for Balance Adjustment",
        "ContractAmount": "Contract Amount",
        "OverdueFee": "Overdue Fee",
        "RepaidAmount": "Repaid Amount",
        "RemainingAmount": "Remaining Amount",
        "Remark": "Remark",
        "PleaseEnterRemark": "Please Enter Remark",

        "GetRepaymentLink": "Get Repayment Link",
        "Name": "Name",
        "ProductName": "Product Name",
        "OrderNumber": "Order Number",
        "PaymentType": "Payment Type",
        "FullRepayment": "Full Repayment",
        "ExtendedRepayment": "Extended Repayment",
        "PartialRepayment": "Partial Repayment",
        "PaymentAmount": "Payment Amount",
        "Generate": "Generate",
        "PaymentLink": "Payment Link",
        "Copy": "Copy",
        "ScriptText": "Script Text",
        "AutoGenerateScript": "Auto Generate Script",
        "RepaymentLinkButton": "Repayment Link",
        "PleaseEnterAmount": "Please Enter Amount",
        "GenerateRepaymentLink": "Generate Repayment Link",

        "ApplyForWaiver": "Apply for Waiver",
        "ContractAmount": "Contract Amount",
        "OverdueFee": "Overdue Fee",
        "RepaidAmount": "Repaid Amount",
        "RemainingAmount": "Remaining Amount",
        "ReductionAmount": "Reduction Amount",
        "Remark": "Remark",
        "PleaseEnterReductionAmount": "Please Enter Reduction Amount",
        "PleaseEnterRemark": "Please Enter Remark",

        "ApplyForBalanceAdjustmentSuccess": "Apply for Balance Adjustment Success",
        "ApplyForBalanceAdjustmentFailed": "Apply for Balance Adjustment Failed",
        "ApplyForReductionSuccess": "Apply for Reduction Success",
        "ApplyForReductionFailed": "Apply for Reduction Failed",

        reduction: {
            applyDate: "Application Date",
            startDate: "Start Date",
            endDate: "End Date",
            auditStatus: "Audit Status",
            all: "All",
            pending: "Pending",
            approved: "Approved",
            rejected: "Rejected",
            query: "Query",
            reset: "Reset",
            applicationType: "Application Type",
            reduction: "Reduction",
            balanceAdjustment: "Balance Adjustment",
            executionResult: "Execution Result",
            success: "Success",
            failure: "Failure",
            orderId: "Order ID",
            applicationTime: "Application Time",
            repayTime: "Repay Time",
            contractAmount: "Contract Amount",
            amount: "Amount",
            operation: "Operation",
            audit: "Audit",
            notExecuted: "Not Executed",
            "submitSuccess": "submit success",
            "submitFailed": "submit failed"
        },
        reductionAudit: {
            title: 'Reduction Audit',
            contractAmount: 'Contract Amount',
            overdueAmount: 'Overdue Amount',
            repaidAmount: 'Repaid Amount',
            remainingAmount: 'Remaining Amount',
            reductionAmount: 'Reduction Amount',
            squareAccountAmount: 'Square Account Amount',
            squareAccountTime: 'Square Account time',
            remark: 'Remark',
            reject: 'Reject',
            approve: 'Approve'
        },
        "currentBillAmount": "Current Bill Amount",
        "lastLoginTime": "Last time the app was opened",
        "lastRequestRepaymentTime": "Last payment code acquisition time",
        "isContactable": "Is Contactable",
        "todayRepayment": "Today's Repayment",
        "followUpCounts": "Follow-up Counts",
        "followUpResults": "Follow-up Results",
        "PTPTime": "PTP Time",
        "followUpRecord": "Follow-up Record",
        "lastFollowUpTime": "Last Follow-up Time",
        "collector": "Follow up people",
        "repaymentPlanID": "Repayment Plan ID",
        "orderTags": "Order Tags",
        "is_today_repay": "Repaying Today",
        "ptp_time": "Repayment Time",
        "can_contract": "Can Contact",
        "detail": "detail",
        "table": {
            "index": "No.",
            "remindTime": "Reminder Time",
            "remindAccount": "Reminder Account",
            "userID": "User ID",
            "repaymentPlanID": "Repayment Plan ID",
            "orderTag": "Order Tag",
            "username": "Username",
            "app": "App",
            "contractAmount": "Contract Amount",
            "overdueFee": "Overdue Fee",
            "overdueStage": "Overdue Stage",
            "overdueDays": "Overdue Days",
            "currentAmount": "Current Amount Due",
            "repaymentType": "Repayment Type",
            "accountAmount": "Account Amount",
            "reducedAmount": "Reduced Amount",
            "followUpResults": "Follow-Up Results",
            "followUpRecord": "Follow-Up Record",
            "actions": "Actions",
            "detail": "Detail",
            "ext": "Ext Repay",
            "repay": "Repay"
        },
        follow_up_people: "follow up people",
        loanTypes: {
            pureNew: "Pure New",   // 纯新
            oldToNew: "Old to New", // 老转新
            reloan: "Reloan",       // 复贷
            extension: "Extension"  // 展期
        },
        collectionTime: 'Collection Time',
        repaymentType: 'Repayment Type',
        "name": "Name",
        "phone": "Phone",
        "totalCallTime": "Total Call Time",
        "lastCallTime": "Last Call Time",
        "recentCallCount": "Total calls",
        "contractList": "Contacts",
        loan_voucher: 'Loan Voucher',
        loan_voucher_details: 'Loan Voucher Details',
        status: 'Status',
        loan_initiation_time: 'Loan Initiation Time',
        transfer_information: 'Transfer Information',
        merchant_order_number: 'Merchant Order Number',
        recipient_account_name: 'Recipient Account Name',
        recipient_type: 'Recipient Type',
        recipient_account_number: 'Recipient Account Number',
        close: 'Close',
        "loan_status": {
            "pending_repay": "Pending Repay",
            "overdue": "Overdue",
            "settle": "Settle",
            "exhibition_receipts": "Exhibition Receipts",
            "square_account": "Square Account",
            "undefined": "Undefined"
        },
        "pleaseChoose": "please choose",
        "timerH": "Scheduled Allocation: Hour",
        "timerM": "Scheduled Allocation: Minute",
        "timerEdit": "Edit Scheduled Allocation Time",
        "callback_loan_initiation_time": "Callback Loan Initiation Time",
        "loan_amount": "Loan Amount",
        "back": "Back",
        IFSC: "IFSC",
        Validation: {
            FollowUpTarget: "Please select a follow up target",
            FollowUpResult: "Please select a follow up result",
            FollowUpNote: "Please enter follow up record",
            PTPTime: "Please select Repayment Time",
        },
        PayStatus: {
            NonPayment: "Non Payment",
            Payment: "Payment",
            PaymentFailure: "Payment Failure",
        },
        RepaymentMethods: {
            Background: "background",
            User: "user"
        },
        RepaymentTypes: {
            Normal: "normal",
            Prepayment: "prepayment",
            Overdue: "overdue"
        },
        Marketing: {
            fileName: "fileName",
            distributable: "distributable",
            distribute: "distribute",
            distributed: "distributed",
            notDistributed: "not distributed",
            totalUserCount: "total user count",
            distributedUserCount: "distributed user count",
            notDistributedUserCount: "not distributed user count",
            registerTime: "register time",
            followUpTime: "follow Up Time",
            followUp: "follow Up",
            followUpTag: "follow Up Tag",
            account: "account",
            registrationStatus: "Registration Status",
            unregistered: "unregistered",
            registered: "registered",
            authentication: "authentication",
            notApply: "Not applied",
            applied: "Applied",
            followed: "followed",
            notFollowed: "not Followed",
            todayFollowed: "today Followed",
            todayRegistered: "today Registered",
            todayApplied: "today Applied",
            todayLoan: "today Loan",
            distribute: "distribute",
            distributeSuccess: "distribute Success",
            distributeFail: "distribute Fail",
            salesman: "salesman",
            marketingManagement: "marketing Management",
            MarketingAgency: "Marketing Agency",
            MarketingProgram: "Marketing Program",
            MarketingStaff: "Marketing Staff",
            MarketingList: "Marketing List",
            MarketingData: "Marketing Data",
            MarketingDistribution: "Marketing Distribution",
            PleaseSelectMechanism: "Please Select Mechanism",
        },
        User: {
            System: "User System",
        },
    },
};